apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginSearchWidget
spec:
  enabled: true
  version: 1.0.0-SNAPSHOT
  requires: "*"
  author: halo-dev
  logo: https://halo.run/logo
  homepage: https://github.com/halo-sigs/plugin-search-widget
  displayName: "搜索组件"
  description: "为 Halo 2.0 提供统一的搜索组件，方便主题端使用。"
  license:
    - name: "MIT"
